# Generated by Django 6.0.6 on 2026-07-04 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('hod', models.CharField(max_length=100)),
                ('total_students', models.PositiveIntegerField(default=0)),
                ('total_faculty', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='College',
        ),
    ]
